import SideBar from "@/components/sidebar/sidebar";
import AuthModal from "@/components/auth-flow/auth-modal";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import { AuthProvider } from "@/context/auth-context";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body>
        <AuthProvider>
          <AuthModal></AuthModal>
          <SideBar></SideBar>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
